* REVSTAMP.H
* Revision information
* Copyright (c) 2007 Ladybridge Systems, All Rights Reserved
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 3, or (at your option)
* any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software Foundation,
* Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
* 
* START-HISTORY:
* 31 Dec 23 SD launch - prior history suppressed
* END-HISTORY
*
* START-DESCRIPTION:
*
* END-DESCRIPTION
*
* START-CODE



$define MAJOR.REV      2
$define MINOR.REV      6
$define BUILD          6
$define VM.REV.STAMP   "2.6-6"
$define SD.REV.STAMP   "0.7.1"

$define SD.COPYRIGHT.YEAR "2007"

* END-CODE 
